language: rust
rust:
  - nightly
  - beta
  - stable
services:
  - redis-server
script:
  - cargo test
  - cargo doc --no-deps
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_RUST_VERSION == "nightly" && ./.travis/update_docs.sh